elkx:
  #image: sebp/elkx:540
  image: sebp/elk:540
  environment:   
    ES_HEAP_SIZE: "2g"

    ELASTICSEARCH_START: 1  #0:es not be started
    LOGSTASH_START: 1       #0:logstash not be started
    KIBANA_START: 1         #0:logstash not be started

    TZ: "Asia/Shanghai"
    MAX_OPEN_FILES: 65536   #maximum number of open files
    ES_CONNECT_RETRY: 10
  volumes:
    - ./etc/default/elasticsearch:/etc/default/elasticsearch
    - ./etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    - ./etc/logstash:/etc/logstash
    - ./etc/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml

    - ./data:/var/lib/elasticsearch/
    - ./log:/var/log/

  ports:
    - "127.0.0.1:5601:5601" #kibana
    - "5044:5044" #logstash
    - "127.0.0.1:9200:9200" #es
    - "127.0.0.1:9300:9300" #es cluter
