#=========================== Filebeat prospectors =============================

filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/nginx/*access.log

  document_type: nginx-access

#================================ Outputs =====================================
#----------------------------- Elasticsearch output --------------------------------

output.elasticsearch:
  enabled: false
  hosts: ["http://localhost:9200"]
  template.enabled: false

  username: "elastic"
  password: "changeme"

#----------------------------- Logstash output --------------------------------
output.logstash:
  enabled: true
  hosts: ["localhost:5044"]
  timeout: 15

